INSERT INTO Applicants (name,
                        surname,
                        email,
                        idNumber,
                        cellphone,
                        birthday,
                        ethnicity,
                        gender,
                        campus,
                        citizen,
                        citizenship)
VALUES ('Arata',
        'Yano',
        'aratayano00@gmail.com',
        '0003235166083',
        '0762470205',
        '2000-03-23',
        'COLOURED',
        'MALE',
        '02',
        'y',
        'South Africa');

INSERT INTO Applicants (name,
                        surname,
                        email,
                        idNumber,
                        cellphone,
                        birthday,
                        ethnicity,
                        gender,
                        campus,
                        citizen,
                        citizenship)
VALUES ('Glen',
        'Wasserfall',
        'glen@wasserfall.com',
        '9511125166834',
        '0845168524',
        '1995-11-12',
        'WHITE',
        'MALE',
        '02',
        'y',
        'South Africa');

INSERT INTO Applicants (name,
                        surname,
                        email,
                        idNumber,
                        cellphone,
                        birthday,
                        ethnicity,
                        gender,
                        campus,
                        citizen,
                        citizenship)
VALUES ('Carah',
        'Prinsloo',
        'carahprinsloo@gmail.com',
        '9905045166064',
        '0842670205',
        '1999-05-04',
        'WHITE',
        'FEMALE',
        '02',
        'y',
        'South Africa');

INSERT INTO Applicants (name,
                        surname,
                        email,
                        idNumber,
                        cellphone,
                        birthday,
                        ethnicity,
                        gender,
                        campus,
                        citizen,
                        citizenship)
VALUES ('Rachel',
        'Bolton',
        'rachelericabolton@gmail.com',
        '9602055164865',
        '0635198754',
        '1996-02-05',
        'WHITE',
        'FEMALE',
        '02',
        'y',
        'South Africa');

INSERT INTO QuestionStore (questionID,
                           active,
                           category,
                           question,
                           optionA,
                           optionB,
                           optionC,
                           optionD,
                           answer)
VALUES ('1',
        '1',
        'deductive reasoning',
        'What is 9 + 10?',
        '109',
        '19',
        '21',
        '910',
        'B');

INSERT INTO QuestionStore (questionID,
                           active,
                           category,
                           question,
                           optionA,
                           optionB,
                           optionC,
                           optionD,
                           answer)
VALUES ('2',
        '1',
        'inductive reasoning',
        'Where does the sun set?',
        'In the North',
        'In the South',
        'In the West',
        'In the East',
        'C');

INSERT INTO QuestionStore (questionID,
                           active,
                           category,
                           question,
                           optionA,
                           optionB,
                           optionC,
                           optionD,
                           answer)
VALUES ('3',
        '1',
        'arithmetic ability',
        'What is the next number in the sequence: 2, 4, 7, 11, ..?',
        '12',
        '9',
        '19',
        '16',
        'D');

INSERT INTO QuestionStore (questionID,
                           active,
                           category,
                           question,
                           optionA,
                           optionB,
                           optionC,
                           optionD,
                           answer)
VALUES ('4',
        '1',
        'programming aptitude',
        'If ADD = 9, BAD = 7 and CAD = 8 what is the value of ADA?',
        '7',
        '6',
        '5',
        '11',
        'C');

UPDATE QuestionStore SET answer = 7 WHERE ID = 1;

DELETE FROM QuestionStore WHERE ID = 1;